name: student_app
description: A modern student management app with Material 3 design
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter



  # State Management
  flutter_riverpod: ^2.4.9

  # UI & Animations
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_animate: ^4.3.0
  lottie: ^2.7.0
  shimmer: ^3.0.0
  flutter_native_splash: ^2.4.0 # Added for native splash screen

  # Storage & Data
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2

  # Network & API
  dio: ^5.4.0
  connectivity_plus: ^5.0.2

  # Phone & Country Code
  country_code_picker: ^3.0.0
  intl_phone_field: ^3.2.0

  # Icons & Images
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0

  # Utilities
  intl: ^0.19.0
  uuid: ^4.2.2
  url_launcher: ^6.2.2
  google_sign_in: ^7.1.1
  confetti: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/school_logo.png
    - assets/images/DiGiSchool_logo.png
    - assets/animations/
    - assets/icons/

# Configuration for the native splash screen
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/school_logo.png
  android: true
  ios: true

